//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerInsights.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagerInsights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Aktuelles_BWB_2016 {
            get {
                object obj = ResourceManager.GetObject("Aktuelles_BWB_2016", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Auswertungsbogen {
            get {
                object obj = ResourceManager.GetObject("Auswertungsbogen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] CheckUpZelt {
            get {
                object obj = ResourceManager.GetObject("CheckUpZelt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Deutsche_Jugendfeuerwehr {
            get {
                object obj = ResourceManager.GetObject("Deutsche_Jugendfeuerwehr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] DJF_Wettbewerbsordnung_BWB_2013 {
            get {
                object obj = ResourceManager.GetObject("DJF_Wettbewerbsordnung_BWB_2013", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4;
        ///            margi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GeburtstagsListe {
            get {
                return ResourceManager.GetString("GeburtstagsListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;
        ///    &lt;td style=&quot;padding-left: 2mm; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {name}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {feuerwehr}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {alter}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {geburtsdatum}
        ///    &lt;/td&gt;
        ///&lt;/tr&gt; ähnelt.
        /// </summary>
        internal static string GeburtstagslisteTabellenzeile {
            get {
                return ResourceManager.GetString("GeburtstagslisteTabellenzeile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Gruppendaten {
            get {
                object obj = ResourceManager.GetObject("Gruppendaten", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4 landscape;
        ///        [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Kontrollblatt {
            get {
                return ResourceManager.GetString("Kontrollblatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;
        ///    &lt;td style=&quot;text-align: right; padding-right: 2mm; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {nr}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {vorname}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {nachname}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {geschlecht}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string KontrollblattTabellenzeile {
            get {
                return ResourceManager.GetString("KontrollblattTabellenzeile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Meldebogen_Blanko {
            get {
                object obj = ResourceManager.GetObject("Meldebogen_Blanko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4;
        ///            margi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlatzierungsListe {
            get {
                return ResourceManager.GetString("PlatzierungsListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] PlatzierungslisteExcel {
            get {
                object obj = ResourceManager.GetObject("PlatzierungslisteExcel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;
        ///    &lt;td style=&quot;text-align: right; padding-right: 2mm; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {lagernr}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {gruppenname}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {ort}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {teilnehmende}
        ///    &lt;/td&gt;
        ///&lt;/tr&gt; ähnelt.
        /// </summary>
        internal static string PlatzierungsListeTabellenzeile {
            get {
                return ResourceManager.GetString("PlatzierungsListeTabellenzeile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4;
        ///            margi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string UnvertraeglichkeitenListe {
            get {
                return ResourceManager.GetString("UnvertraeglichkeitenListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;
        ///    &lt;td style=&quot;padding-left: 2mm; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {name}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {feuerwehr}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {alter}
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;white-space: nowrap; text-overflow: ellipsis; overflow: hidden;&quot;&gt;
        ///        {geburtsdatum}
        ///    &lt;/td&gt;
        ///&lt;/tr&gt; ähnelt.
        /// </summary>
        internal static string UnvertraeglichkeitenlisteTabellenzeile {
            get {
                return ResourceManager.GetString("UnvertraeglichkeitenlisteTabellenzeile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] UrkundeDruckTheme1 {
            get {
                object obj = ResourceManager.GetObject("UrkundeDruckTheme1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Urkundenliste {
            get {
                object obj = ResourceManager.GetObject("Urkundenliste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Urkundenpapier_BeispielDruck {
            get {
                object obj = ResourceManager.GetObject("Urkundenpapier_BeispielDruck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Urkundenpapier_BeispielIndesign {
            get {
                object obj = ResourceManager.GetObject("Urkundenpapier_BeispielIndesign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] UrkundeOriginalTheme1 {
            get {
                object obj = ResourceManager.GetObject("UrkundeOriginalTheme1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4;
        ///            margi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string UrkundeOverlay {
            get {
                return ResourceManager.GetString("UrkundeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4;
        ///            margi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string UrkundeOverlayJuengsteGruppe {
            get {
                return ResourceManager.GetString("UrkundeOverlayJuengsteGruppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Open+Sans&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            size: A4;
        ///            margi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string UrkundeOverlayTheme1 {
            get {
                return ResourceManager.GetString("UrkundeOverlayTheme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Wettbewerbsinfo {
            get {
                object obj = ResourceManager.GetObject("Wettbewerbsinfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Wettbewerbsrichtlinien {
            get {
                object obj = ResourceManager.GetObject("Wettbewerbsrichtlinien", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
