<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>BWB_Auswertung</RootNamespace>
    <Nullable>annotations</Nullable>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <ApplicationIcon>Resources\Images\App.ico</ApplicationIcon>
	<NeutralLanguage>de-DE</NeutralLanguage>
	<StartupObject>BWB_Auswertung.App</StartupObject>
	<AssemblyVersion>1.1.1</AssemblyVersion>
	<FileVersion>1.1.1</FileVersion>
	<AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="Resources\BWB.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\Deutsche_Jugendfeuerwehr.ico" />
    <Content Include="Resources\Images\Logo_Freigestellt_small.png" />
    <Content Include="Resources\Images\Logo_Freigestellt.png" />
    <Content Include="Resources\Images\Logo_mit_Rand.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="itext.pdfhtml" Version="6.3.2" />
    <PackageReference Include="MahApps.Metro" Version="3.0.0-rc0529" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.FontAwesome" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Modern" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Octicons" Version="6.2.1" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="PuppeteerSharp" Version="25.0.4" />
    <PackageReference Include="ReactiveUI" Version="23.2.27" />
    <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="1.3.1" />
    <PackageReference Include="ReactiveUI.WPF" Version="23.2.27" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Wettbewerbsordnung\" />
    <Folder Include="Resources\Themes\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\Images\icon.png" Pack="true" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="NuGet.CommandLine" Version="6.9.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SSH.NET" Version="2025.1.0" />
	</ItemGroup>

	<PropertyGroup>
		<NugetTools>$(PkgNuGet_CommandLine)\tools</NugetTools>
		<SquirrelTools>$(Pkgsquirrel_windows)\tools</SquirrelTools>

		<Version>1.1.1</Version>

		<NuspecFile>$(ProjectDir)ReleaseSpec.nuspec</NuspecFile>
	</PropertyGroup>

	<Target Name="GenerateRelease" AfterTargets="AfterBuild" Condition="$(Configuration) == Release">
		<XmlPeek XmlInputPath="$(NuspecFile)" Query="/package/metadata/id/text()">
			<Output TaskParameter="Result" ItemName="ID" />
		</XmlPeek>

		<Exec Command="&quot;$(NugetTools)\NuGet.exe&quot; pack &quot;$(NuspecFile)&quot; -Version $(Version) -Properties Configuration=Release -OutputDirectory &quot;$(ProjectDir)Deployment\GeneratedNugets&quot;" />

	</Target>
</Project>
